      SUBROUTINE UPCASE(KEYWRD)
      CHARACTER*241 KEYWRD
      ICAPA=ICHAR('A')
      ILOWA=ICHAR('a')
      ILOWZ=ICHAR('z')
      DO 10 I=1,241
         ILINE=ICHAR(KEYWRD(I:I))
         IF(ILINE.GE.ILOWA.AND.ILINE.LE.ILOWZ) THEN
            KEYWRD(I:I)=CHAR(ILINE+ICAPA-ILOWA)
         ENDIF
   10 CONTINUE
      RETURN
      END
